# -*- coding: utf-8 -*-
"""Contenu des carrousels du planning BTP Expertise (octobre - novembre 2026).

Sources relues le 2026-10-08 sur le site en ligne : /reglement/ (tarifs), /amo/,
/conseils/episodes-mediterraneens-preparer-toiture-etancheite/,
/conseils/expertise-avant-achat-points-a-verifier/,
/conseils/reception-travaux-reserves-garanties/.
Les montants des couvertures « devis » sont fictifs et marqués comme tels.
"""

DEVIS_PIED = "Devis établi avant toute intervention."
PRIX_DESORDRES = "<b>Expertise désordres &amp; malfaçons à partir de 1 200 € TTC.</b> " + DEVIS_PIED
PRIX_AMO = ("<b>AMO : 5 à 8 % du montant HT des travaux</b>, minimum 3 500 € HT. " + DEVIS_PIED)
PASTILLE_FIN = "EXPERTISE INDÉPENDANTE SUR LA CÔTE D'AZUR"
DESORDRES = "LES DÉSORDRES DU BÂTIMENT"
AMO = "ASSISTANCE À MAÎTRISE D'OUVRAGE"

CARROUSELS = [
    {
        # Republication corrigée du carrousel du 08/10 (l'original citait une visite à 590 €).
        "slug": "2026-10-fissures-v3",
        "diapos": [
            {"type": "couverture", "photo": "visite-12.jpg", "pastille": DESORDRES,
             "titre": "Cette fissure s'élargit<br><span class=\"o\">chaque été.</span>",
             "chapo": "Et se referme presque l'hiver. Ce n'est pas le mur qui hésite : c'est le sol qui bouge."},
            {"type": "duo", "surtitre": "Le mécanisme", "titre": "L'argile <span class=\"b\">respire</span> avec les saisons",
             "chapo": "Le retrait-gonflement des argiles fait travailler les fondations, au rythme de la météo.",
             "items": [("alerte", "Été sec", "L'argile perd son eau et se rétracte. Le sol se dérobe sous une partie des fondations."),
                       ("goutte", "Hiver humide", "L'argile se gorge d'eau et regonfle. La fissure se referme en partie, puis tout recommence.")],
             "encadre": "Dans les Alpes-Maritimes et le Var, de nombreuses communes sont exposées à ce phénomène."},
            {"type": "frise", "gris": True, "surtitre": "Ce qui doit alerter", "titre": "Les signes à <span class=\"o\">surveiller</span>",
             "items": [("Fissure en escalier", "Dans les joints, ou en biais près des angles."),
                       ("Menuiseries qui coincent", "Portes et fenêtres dures l'été, normales l'hiver."),
                       ("Terrasse qui se décolle", "Un joint qui s'ouvre entre le dallage et la maison."),
                       ("Ouverture irrégulière", "Une fissure plus large à une extrémité qu'à l'autre."),
                       ("Variation saisonnière", "Elle s'ouvre et se referme au fil de l'année.")]},
            {"type": "cartes", "surtitre": "Les réflexes à éviter", "titre": "Ce qui <span class=\"o\">aggrave</span> le dossier",
             "items": [("x", "Reboucher tout de suite", "L'enduit masque l'indice qui permet de comprendre ce qui se passe."),
                       ("x", "Attendre « pour voir »", "Une fissure active évolue rarement seule dans le bon sens."),
                       ("x", "Ignorer arbres et fuites", "Près des fondations, ils assèchent ou détrempent le sol de façon irrégulière.")]},
            {"type": "frise", "couleur": "orange", "gris": True, "surtitre": "Dès aujourd'hui", "titre": "Ce que vous pouvez <span class=\"b\">faire</span>",
             "items": [("Photographier", "Avec un repère (règle, pièce) et la date."),
                       ("Marquer les extrémités", "Un trait de crayon, la date écrite à côté."),
                       ("Mesurer l'ouverture", "Régulièrement, été comme hiver."),
                       ("Surveiller les arrêtés", "Catastrophe naturelle sécheresse : la déclaration à l'assureur a un délai.")]},
            {"type": "cartes", "couleur": "bleu", "etiquette": "J'AI UN PROBLÈME", "titre": "Comprendre avant de <span class=\"b\">réparer</span>",
             "items": [("loupe", "Constater", "Relevés, photographies, cartographie des fissures."),
                       ("barres", "Analyser", "Superficielle ou structurelle, active ou stabilisée, et sa cause probable."),
                       ("doc", "Préconiser", "Surveillance, étude de sol ou reprise : la suite adaptée, expliquée simplement.")]},
            {"type": "contact", "photo": "visite-12.jpg", "pastille": PASTILLE_FIN,
             "titre": "Une fissure qui évolue ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Un regard technique indépendant pour comprendre votre bâtiment et décider en connaissance de cause.",
             "prix": PRIX_DESORDRES},
        ],
    },
    {
        "slug": "2026-10-13-toiture",
        "diapos": [
            {"type": "couverture", "photo": "visite-15.jpg", "pastille": DESORDRES,
             "titre": "Une heure de pluie.<br><span class=\"o\">Un mois d'eau.</span>",
             "chapo": "Les épisodes méditerranéens révèlent les faiblesses des toitures. Le moment de vérifier, c'est avant."},
            {"type": "cartes", "surtitre": "Le bâti local", "titre": "Trois points <span class=\"b\">faibles</span> sur la Côte d'Azur",
             "items": [("maison", "Toitures-terrasses", "Peu de descentes : une seule bouchée, et l'eau stagne sur plusieurs centimètres."),
                       ("pente", "Terrains en pente", "Le ruissellement converge vers les constructions en contrebas."),
                       ("ajout", "Extensions et vérandas", "Le raccord avec l'existant est le point faible classique.")]},
            {"type": "frise", "gris": True, "surtitre": "Depuis le sol, sans monter", "titre": "Ce que vous pouvez <span class=\"o\">vérifier</span>",
             "items": [("Évacuations", "Gouttières encombrées, crapaudines absentes, descentes fendues."),
                       ("Façades", "Coulures sous les débords, auréoles en pied de mur."),
                       ("Appuis de fenêtre", "Une pente insuffisante renvoie l'eau vers la menuiserie."),
                       ("Abords", "Regards bouchés, terrain qui penche vers la maison."),
                       ("Plafonds sous toiture", "Une auréole, même ancienne, signale un chemin d'eau.")]},
            {"type": "cartes", "couleur": "bleu", "etiquette": "LE REGARD D'UN PROFESSIONNEL",
             "titre": "Là où l'eau <span class=\"b\">passe</span> le plus souvent",
             "items": [("loupe", "Relevés d'étanchéité", "Hauteur, fixation en tête, vieillissement : ils se contrôlent de près."),
                       ("maison", "Solins et zinguerie", "Souches de cheminée, noues, tuiles déplacées par le vent."),
                       ("doc", "Mise en œuvre", "Une étanchéité mal relevée n'est pas une fatalité : c'est un défaut d'exécution.")]},
            {"type": "frise", "couleur": "orange", "gris": True, "surtitre": "Si l'eau est entrée",
             "titre": "Les 3 gestes qui <span class=\"o\">comptent</span>",
             "items": [("Photographier", "Traces, niveaux atteints, biens touchés : avant tout nettoyage."),
                       ("Déclarer", "À l'assureur, dans les délais du contrat, sans attendre de connaître l'origine."),
                       ("Vérifier l'arrêté", "Catastrophe naturelle : sa publication ouvre un délai spécifique.")],
             "cle": "Vérifier avant coûte le prix d'une visite. Constater après coûte le prix des travaux."},
            {"type": "contact", "photo": "visite-15.jpg", "pastille": PASTILLE_FIN,
             "titre": "Une auréole au plafond ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Un regard technique indépendant, avant la saison ou après un sinistre.", "prix": PRIX_DESORDRES},
        ],
    },
    {
        "slug": "2026-10-15-amo-devis",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "devis-bureau.jpg", "cadrage": "center top", "pastille": AMO, "taille": 84,
             "titre": "Trois devis. Trois prix.<br><span class=\"o\">Lequel choisir ?</span>",
             "chapo": "Le moins cher n'est pas toujours le bon. Le plus cher non plus."},
            {"type": "cartes", "surtitre": "Le piège", "titre": "Comparer des prix, <span class=\"o\">pas</span> des prestations",
             "items": [("x", "Des périmètres différents", "L'un compte la dépose et l'évacuation, l'autre les oublie."),
                       ("x", "Des quantités floues", "« Forfait » ou « ensemble », sans métré ni détail."),
                       ("x", "Des matériaux non précisés", "« Carrelage » ne dit ni la gamme, ni le format, ni la pose.")]},
            {"type": "frise", "gris": True, "surtitre": "Ce qu'on vérifie", "titre": "Lire un devis <span class=\"o\">ligne par ligne</span>",
             "items": [("Périmètre", "Ce qui est prévu, et surtout ce qui ne l'est pas."),
                       ("Quantités", "Des métrés cohérents avec votre projet."),
                       ("Matériaux et mise en œuvre", "Des références précises, conformes aux règles de l'art."),
                       ("Assurances", "Une attestation décennale valide pour l'activité."),
                       ("Délais et paiements", "Un calendrier et des acomptes réalistes.")]},
            {"type": "cartes", "couleur": "bleu", "etiquette": "J'AI UN PROJET", "etiquette_couleur": "orange",
             "titre": "Vous restez <span class=\"b\">décisionnaire</span>",
             "chapo": "BTP Expertise conseille et assiste. Vous contractez directement avec les entreprises.",
             "items": [("barres", "Comparaison", "Technique et financière, offre par offre."),
                       ("doc", "Conseil", "Une analyse des offres avant votre décision."),
                       ("ok", "Indépendance", "Le cabinet n'est pas rémunéré par les entreprises.")]},
            {"type": "frise", "couleur": "orange", "gris": True, "surtitre": "L'AMO, étape par étape",
             "titre": "De l'idée à la <span class=\"o\">réception</span>",
             "items": [("Étude du projet", "Besoins, objectifs, contraintes et priorités."),
                       ("Consultation des entreprises", "Recherche et mise en concurrence."),
                       ("Analyse des devis", "Comparaison technique et financière."),
                       ("Suivi des travaux", "Visites sur site et comptes rendus."),
                       ("Assistance à réception", "Formulation des réserves.")]},
            {"type": "contact", "photo": "devis-bureau.jpg", "pastille": PASTILLE_FIN,
             "titre": "Des devis à comparer ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Un regard technique indépendant pour choisir en connaissance de cause.", "prix": PRIX_AMO},
        ],
    },
    {
        "slug": "2026-10-20-facade",
        "diapos": [
            {"type": "couverture", "photo": "visite-14.jpg", "pastille": DESORDRES,
             "titre": "Après l'orage,<br><span class=\"o\">le mur pleure.</span>",
             "chapo": "Coulures, auréoles, salpêtre : la façade raconte par où l'eau est passée."},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Lire les traces", "titre": "Chaque trace a son <span class=\"b\">origine</span>",
             "items": [("goutte", "Coulures verticales", "Sous un débord : l'eau de toiture est mal évacuée."),
                       ("goutte", "Auréoles en pied de mur", "Rejaillissement ou humidité qui remonte."),
                       ("goutte", "Autour des fenêtres", "Un appui ou un joint défaillant."),
                       ("goutte", "Fissures d'enduit", "Une porte d'entrée pour la pluie battante.")]},
            {"type": "frise", "gris": True, "surtitre": "Les points sensibles", "titre": "Par où l'eau <span class=\"o\">entre</span>",
             "items": [("Appuis de fenêtre", "Rejingot usé ou pente insuffisante."),
                       ("Descentes pluviales", "Fendues, bouchées ou désolidarisées du mur."),
                       ("Enduit et joints", "Fissures, décollements, joints creusés."),
                       ("Jonctions", "Entre la façade et la toiture, ou une extension.")]},
            {"type": "cartes", "surtitre": "À éviter", "titre": "Repeindre ne <span class=\"o\">soigne</span> rien",
             "items": [("x", "Repeindre par-dessus", "La trace revient, la cause reste."),
                       ("x", "Traiter sans diagnostic", "Un produit mal choisi peut enfermer l'humidité dans le mur."),
                       ("x", "Laisser passer l'hiver", "Un enduit gorgé d'eau se dégrade, et laisse passer davantage.")]},
            {"type": "frise", "couleur": "orange", "gris": True, "surtitre": "Le bon réflexe", "titre": "Observer, puis <span class=\"o\">comprendre</span>",
             "items": [("Photographier", "Après chaque épisode de pluie, au même endroit."),
                       ("Noter", "Où, quand, et par quel vent la trace apparaît."),
                       ("Faire identifier la cause", "Avant de choisir les travaux.")]},
            {"type": "contact", "photo": "visite-14.jpg", "pastille": PASTILLE_FIN,
             "titre": "Une façade qui marque ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Constater, analyser, préconiser : la bonne réparation au bon endroit.", "prix": PRIX_DESORDRES},
        ],
    },
    {
        "slug": "2026-10-22-reception",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "visite-10.jpg", "pastille": AMO,
             "titre": "Le jour de la réception,<br><span class=\"o\">tout se joue.</span>",
             "chapo": "Ce que vous ne signalez pas ce jour-là est réputé accepté."},
            {"type": "frise", "surtitre": "Ce que la signature déclenche", "titre": "Bien plus qu'une <span class=\"o\">formalité</span>",
             "items": [("Le transfert de la garde", "Le bâtiment devient le vôtre, avec ses risques."),
                       ("Le départ des garanties", "Parfait achèvement 1 an, bon fonctionnement 2 ans, décennale 10 ans."),
                       ("Le solde exigible", "Sous réserve de la retenue de garantie.")]},
            {"type": "duo", "gris": True, "surtitre": "Apparent ou caché", "titre": "La différence qui <span class=\"b\">coûte cher</span>",
             "items": [("alerte", "Défaut apparent", "Visible le jour J : à relever, sinon réputé accepté."),
                       ("loupe", "Défaut caché", "Invisible ce jour-là : il reste couvert par les garanties.")],
             "encadre": "Encore faut-il prouver qu'il ne pouvait pas être vu : d'où l'intérêt d'un procès-verbal précis."},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Des réserves qui tiennent",
             "titre": "Précises, situées, <span class=\"o\">photographiées</span>",
             "items": [("loupe", "Situer", "La pièce et l'élément concernés."),
                       ("doc", "Décrire", "En termes techniques, pas en impressions."),
                       ("photo", "Photographier", "Chaque réserve, avec un repère d'échelle."),
                       ("cal", "Fixer un délai", "Pour la reprise, inscrit au procès-verbal.")],
             "cle": "« Peinture à revoir » n'engage à rien. « Chambre 2, mur nord : défaut de planéité sur 2 m² » engage l'entreprise."},
            {"type": "cartes", "gris": True, "surtitre": "Attention", "titre": "La réception <span class=\"o\">tacite</span>",
             "chapo": "Pas de réunion de réception ? Cela ne vous protège pas, au contraire.",
             "items": [("alerte", "Emménager", "Prendre possession des lieux…"),
                       ("alerte", "Régler le solde", "…et payer le solde peut valoir réception, sans aucune réserve.")]},
            {"type": "contact", "photo": "visite-10.jpg", "pastille": PASTILLE_FIN,
             "titre": "Une réception à préparer ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Le jour où vous signez, il est trop tard pour ajouter ce que vous n'avez pas vu.",
             "prix": "<b>Assistance à réception de travaux à partir de 750 € TTC.</b> " + DEVIS_PIED},
        ],
    },
    {
        "slug": "2026-10-27-pied-de-mur",
        "diapos": [
            {"type": "couverture", "photo": "visite-16.jpg", "pastille": DESORDRES,
             "titre": "Le bas du mur<br><span class=\"o\">s'effrite.</span>",
             "chapo": "Salpêtre, peinture qui cloque, plinthes qui gonflent : l'humidité monte peut-être du sol."},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Les signes", "titre": "Ce que montre le <span class=\"b\">pied de mur</span>",
             "items": [("goutte", "Une bande humide", "Horizontale, à hauteur à peu près régulière."),
                       ("loupe", "Du salpêtre", "Des dépôts blancs et poudreux."),
                       ("alerte", "Un enduit qui cloque", "Ou une peinture qui se décolle."),
                       ("maison", "Des plinthes qui gonflent", "Ou un doublage qui se déforme.")]},
            {"type": "frise", "gris": True, "surtitre": "Avant de traiter", "titre": "Trois causes, <span class=\"o\">trois</span> remèdes",
             "items": [("Remontées capillaires", "L'eau du sol monte dans la maçonnerie."),
                       ("Infiltration latérale", "Un terrain plus haut que le sol intérieur, sans drainage."),
                       ("Fuite ou condensation", "Une canalisation, ou un mur froid et peu ventilé.")],
             "encadre": "Les traces se ressemblent. Les traitements, eux, n'ont rien à voir."},
            {"type": "cartes", "surtitre": "À éviter", "titre": "Ce qui <span class=\"o\">aggrave</span> le problème",
             "items": [("x", "Un enduit étanche", "Sur un mur ancien, il bloque l'humidité au lieu de la laisser sortir."),
                       ("x", "Un doublage collé", "Il cache la trace, le mur continue de se dégrader derrière."),
                       ("x", "Un traitement au hasard", "Choisi sans connaître la cause.")]},
            {"type": "frise", "couleur": "orange", "gris": True, "surtitre": "Le bon ordre", "titre": "Diagnostiquer, puis <span class=\"o\">traiter</span>",
             "items": [("Constater", "Où, à quelle hauteur, depuis quand."),
                       ("Identifier la cause", "Capillarité, infiltration, fuite ou condensation."),
                       ("Choisir le traitement", "Adapté à la cause et au type de mur."),
                       ("Vérifier la reprise", "Après travaux, dans la durée.")]},
            {"type": "contact", "photo": "visite-16.jpg", "pastille": PASTILLE_FIN,
             "titre": "Un mur qui reste humide ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Comprendre la cause avant de payer le traitement.", "prix": PRIX_DESORDRES},
        ],
    },
    {
        "slug": "2026-10-29-avant-achat",
        "diapos": [
            {"type": "couverture", "photo": "visite-06.jpg", "pastille": "EXPERTISE AVANT ACHAT",
             "titre": "Coup de cœur.<br><span class=\"o\">Offre ce soir ?</span>",
             "chapo": "Les diagnostics obligatoires ne disent presque rien de l'état réel du bâtiment."},
            {"type": "duo", "surtitre": "Deux documents, deux objectifs", "titre": "Diagnostic ou <span class=\"b\">expertise</span> ?",
             "items": [("doc", "Diagnostics obligatoires", "Amiante, plomb, termites, électricité, gaz, DPE, risques. Ils protègent le vendeur."),
                       ("loupe", "Expertise avant achat", "Structure, humidité, toiture, travaux antérieurs, travaux à prévoir. Elle protège l'acheteur.")]},
            {"type": "frise", "gris": True, "surtitre": "Les points examinés", "titre": "Ce que l'expert <span class=\"o\">regarde</span>",
             "items": [("Structure", "Fissures, affaissements, planchers déformés."),
                       ("Humidité", "Remontées, condensation, traces d'infiltration."),
                       ("Couverture et étanchéité", "Tuiles, zinguerie, toitures-terrasses, évacuations."),
                       ("Travaux antérieurs", "Qualité d'exécution, autorisations d'urbanisme."),
                       ("Copropriété", "Parties communes et travaux votés à venir.")]},
            {"type": "cartes", "surtitre": "Les signaux qui font ralentir", "titre": "Là, on <span class=\"o\">prend le temps</span>",
             "items": [("alerte", "Fissures en escalier", "Sur une façade, surtout sur sol argileux."),
                       ("alerte", "Peinture refaite par endroits", "Elle masque parfois une trace d'humidité."),
                       ("alerte", "Extension sans autorisation", "Aucune trace en mairie."),
                       ("alerte", "Plancher qui sonne creux", "Ou qui présente une pente perceptible.")]},
            {"type": "cartes", "couleur": "bleu", "gris": True, "surtitre": "Ce que ça change", "titre": "Le rapport <span class=\"b\">chiffre</span>",
             "items": [("euro", "Pour négocier", "Des travaux à prévoir, chiffrés, changent la discussion sur le prix."),
                       ("cal", "Au bon moment", "Idéalement avant le compromis, quand la marge est la plus large."),
                       ("ok", "Si le bien est sain", "Vous signez sans arrière-pensée.")]},
            {"type": "contact", "photo": "visite-06.jpg", "pastille": PASTILLE_FIN,
             "titre": "Vous visitez un bien ?<br><span class=\"o\">Faites-le expertiser.</span>", "taille": 76,
             "chapo": "Une expertise avant le compromis coûte une fraction d'un désordre découvert après.",
             "prix": "<b>Expertise avant achat à partir de 900 € TTC.</b> " + DEVIS_PIED},
        ],
    },
    {
        "slug": "2026-11-03-malfacon",
        "diapos": [
            {"type": "couverture", "photo": "visite-09.jpg", "pastille": DESORDRES, "taille": 80,
             "titre": "Ça ne me plaît pas.<br><span class=\"o\">Est-ce une malfaçon ?</span>",
             "chapo": "Tout ce qui dérange n'est pas reprochable à l'entreprise. Et inversement."},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Pas forcément une malfaçon",
             "titre": "Un défaut visible n'est <span class=\"b\">pas toujours</span> fautif",
             "items": [("loupe", "Une finition qui déplaît", "Le goût ne fait pas la règle."),
                       ("loupe", "Une tolérance admise", "Certains écarts dimensionnels sont prévus par les normes."),
                       ("loupe", "Un choix discutable", "Mais conforme aux pièces du marché.")]},
            {"type": "frise", "gris": True, "surtitre": "La référence", "titre": "Des <span class=\"o\">règles</span>, pas un ressenti",
             "items": [("DTU et normes", "Les prescriptions techniques applicables."),
                       ("Règles de l'art", "Ce qu'un professionnel doit savoir faire."),
                       ("Pièces du marché", "Devis, descriptif, plans."),
                       ("Notices des fabricants", "Les conditions de pose des produits.")]},
            {"type": "cartes", "surtitre": "Avant de contester", "titre": "D'abord, <span class=\"o\">documenter</span>",
             "items": [("photo", "Photographier", "Dater et situer chaque défaut."),
                       ("doc", "Rassembler", "Devis, factures, échanges écrits."),
                       ("x", "Ne pas faire reprendre", "Par un tiers avant que le constat soit fait.")]},
            {"type": "duo", "gris": True, "surtitre": "Après l'analyse", "titre": "Un constat <span class=\"b\">opposable</span>",
             "items": [("alerte", "C'est une malfaçon", "Le rapport décrit, situe et rattache le défaut aux règles applicables."),
                       ("ok", "Ce n'en est pas une", "Vous le savez, et vous évitez un litige perdu d'avance.")]},
            {"type": "contact", "photo": "visite-09.jpg", "pastille": PASTILLE_FIN,
             "titre": "Un doute sur des travaux ?<br><span class=\"o\">Parlons-en.</span>",
             "chapo": "Distinguer un reproche d'un constat, c'est tout le travail de l'expertise.", "prix": PRIX_DESORDRES},
        ],
    },
    {
        "slug": "2026-11-05-amo-chantier",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "visite-20.jpg", "pastille": AMO, "taille": 80,
             "titre": "Le chantier dérape.<br><span class=\"o\">Qui défend vos intérêts ?</span>",
             "chapo": "Retards, imprévus, avenants : seul face aux entreprises, difficile de savoir quoi accepter."},
            {"type": "cartes", "surtitre": "Les signaux", "titre": "Quand le chantier <span class=\"o\">échappe</span>",
             "items": [("alerte", "Les avenants s'enchaînent", "Sans explication technique."),
                       ("alerte", "Le planning glisse", "Sans nouveau calendrier."),
                       ("alerte", "Les travaux diffèrent du devis", "Matériaux ou prestations remplacés."),
                       ("alerte", "Les acomptes devancent", "L'avancement réel du chantier.")]},
            {"type": "cartes", "couleur": "bleu", "gris": True, "surtitre": "Le rôle de l'AMO",
             "titre": "Un regard technique <span class=\"b\">à vos côtés</span>",
             "items": [("loupe", "Visites sur site", "Et observations techniques."),
                       ("ok", "Contrôle visuel", "De la qualité apparente des travaux."),
                       ("doc", "Comptes rendus", "Points de vigilance et recommandations."),
                       ("cal", "Assistance à réception", "Jusqu'à la formulation des réserves.")]},
            {"type": "duo", "surtitre": "Ce que l'AMO n'est pas", "titre": "Conseiller, <span class=\"o\">pas diriger</span>",
             "items": [("ok", "L'AMO fait", "Observer, alerter, conseiller, vous aider à décider."),
                       ("x", "L'AMO ne fait pas", "Diriger les travaux ou donner des ordres aux entreprises.")],
             "cle": "Vous restez maître de votre projet : vous décidez, vous contractez directement avec les entreprises."},
            {"type": "cartes", "gris": True, "surtitre": "Des projets accompagnés", "titre": "Là où l'AMO <span class=\"o\">sert</span>",
             "items": [("maison", "Rénovation complète", "Consultation, analyse des devis, suivi jusqu'à la réception."),
                       ("goutte", "Remise en état après sinistre", "Définition des reprises, accompagnement face aux intervenants."),
                       ("loupe", "Reprise de fissures", "Comparaison des solutions et contrôle des travaux.")]},
            {"type": "contact", "photo": "visite-20.jpg", "pastille": PASTILLE_FIN,
             "titre": "Un chantier à reprendre en main ?<br><span class=\"o\">Parlons-en.</span>", "taille": 72,
             "chapo": "Il n'est jamais trop tard pour avoir un regard technique de votre côté.", "prix": PRIX_AMO},
        ],
    },

    # --- Réseau. Source : btpexpertise.fr/rejoignez-nous/ et TEXTES-AMO-RECRUTEMENT.md.
    # Toujours « réseau de professionnels indépendants » : jamais « équipe », « poste », « CDI ».
    {
        "slug": "reseau-rejoindre",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Rejoignez le réseau",
             "titre": "Indépendant du bâtiment&nbsp;? Travaillons ensemble",
             "items": ["Expertise, structure, humidité", "Thermique, économie de la construction",
                       "Électricité, plomberie, couverture", "Alpes-Maritimes et Var"],
             "chapo": "Un réseau de professionnels indépendants, mobilisés selon chaque dossier."},
            {"type": "liste", "surtitre": "Profils recherchés", "titre": "Votre <span class=\"b\">spécialité</span> nous intéresse",
             "items": ["Experts bâtiment généralistes", "Ingénieurs structure", "Fissures et structure",
                       "Humidité et étanchéité", "Thermiciens", "Économistes de la construction",
                       "Électricité", "Plomberie", "Couverture", "Assainissement"],
             "encadre": "Et toute autre spécialité technique du bâtiment."},
            {"type": "cartes", "gris": True, "surtitre": "Le principe", "titre": "Indépendant, <span class=\"b\">pas isolé</span>",
             "items": [("maison", "Votre structure", "Vous gardez votre statut et votre responsabilité professionnelle."),
                       ("reseau", "Des dossiers adaptés", "Le cabinet mobilise les compétences selon la spécificité de chaque dossier."),
                       ("doc", "Une méthode commune", "Constater, analyser, préconiser.")]},
            {"type": "frise", "surtitre": "Les prérequis", "titre": "Ce que nous <span class=\"b\">demandons</span>",
             "items": [("Statut indépendant", "Installé à votre compte."),
                       ("Expérience terrain", "Dans votre spécialité."),
                       ("RC professionnelle", "À jour."),
                       ("Secteur", "Alpes-Maritimes (06) et/ou Var (83).")]},
            {"type": "frise", "couleur": "orange", "gris": True, "surtitre": "Candidater", "titre": "Trois étapes, <span class=\"o\">sans engagement</span>",
             "items": [("Présentez votre profil", "Le formulaire en ligne, en quelques minutes."),
                       ("Premier échange", "Par téléphone, sans engagement."),
                       ("Votre CV", "Envoyé après ce premier contact.")]},
            {"type": "contact", "pastille": "CANDIDATURE",
             "titre": "Envie d'en parler ?<br><span class=\"b\">Présentez-nous votre profil.</span>", "taille": 70,
             "chapo": "Nous revenons vers vous pour un premier échange téléphonique, sans engagement.",
             "boutons": ("Rejoignez-nous", "btpexpertise.fr"),
             "prix": "Candidature sur <b>btpexpertise.fr/rejoignez-nous</b> · contact@btpexpertise.fr"},
        ],
    },
    {
        "slug": "reseau-competences",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Notre réseau",
             "titre": "Un dossier, la bonne compétence",
             "items": ["Une fissure : l'expert structure", "Une infiltration : le spécialiste étanchéité",
                       "Un réseau défaillant : le technicien du lot", "Un projet de travaux : l'AMO"],
             "chapo": "Le cabinet mobilise le profil adapté à la spécificité de chaque dossier."},
            {"type": "cartes", "surtitre": "Pourquoi un réseau", "titre": "Plusieurs disciplines, un seul interlocuteur",
             "items": [("loupe", "Pour le client", "Le bon spécialiste, sans chercher seul."),
                       ("reseau", "Pour l'indépendant", "Des dossiers dans sa spécialité, sur son secteur."),
                       ("doc", "Pour tous", "Une même méthode : constater, analyser, préconiser.")]},
            {"type": "liste", "gris": True, "surtitre": "Profils recherchés", "titre": "Votre spécialité manque peut-être",
             "items": ["Ingénieurs structure", "Thermiciens", "Économistes de la construction", "Électricité",
                       "Plomberie", "Couverture", "Assainissement", "Humidité et étanchéité"]},
            {"type": "contact", "pastille": "CANDIDATURE",
             "titre": "Votre spécialité<br><span class=\"b\">nous intéresse.</span>", "taille": 76,
             "chapo": "Un premier échange téléphonique, sans engagement.",
             "boutons": ("Rejoignez-nous", "btpexpertise.fr"),
             "prix": "Candidature sur <b>btpexpertise.fr/rejoignez-nous</b> · contact@btpexpertise.fr"},
        ],
    },
    {
        "slug": "reseau-expert",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Expert bâtiment indépendant",
             "titre": "La pathologie du bâti, c'est votre terrain&nbsp;?",
             "items": ["Fissures et structure", "Humidité et infiltrations", "Malfaçons et litiges travaux",
                       "Rapports écrits, clairs, opposables"],
             "chapo": "Le cabinet cherche des experts indépendants sur les Alpes-Maritimes et le Var."},
            {"type": "cartes", "surtitre": "Le profil", "titre": "Ce qui fait un <span class=\"b\">bon expert</span>",
             "items": [("loupe", "Une formation bâtiment", "Et de l'expérience terrain."),
                       ("goutte", "La pathologie du bâti", "Fissures, humidité, malfaçons."),
                       ("doc", "Un rapport clair", "Qui tienne face à une entreprise, un assureur ou un juge.")]},
            {"type": "cartes", "gris": True, "surtitre": "Le principe", "titre": "Indépendant, <span class=\"b\">pas isolé</span>",
             "items": [("maison", "Votre structure", "Vous gardez votre statut et votre responsabilité professionnelle."),
                       ("reseau", "Des dossiers adaptés", "Le cabinet mobilise les compétences selon chaque dossier."),
                       ("doc", "Une méthode commune", "Constater, analyser, préconiser.")]},
            {"type": "frise", "surtitre": "Les prérequis", "titre": "Ce que nous <span class=\"b\">demandons</span>",
             "items": [("Statut indépendant", "Installé à votre compte."),
                       ("RC professionnelle", "À jour."),
                       ("Secteur", "Alpes-Maritimes (06) et/ou Var (83).")]},
            {"type": "contact", "pastille": "CANDIDATURE",
             "titre": "Votre parcours<br><span class=\"b\">nous intéresse.</span>", "taille": 76,
             "chapo": "Un premier échange téléphonique, sans engagement.",
             "boutons": ("Rejoignez-nous", "btpexpertise.fr"),
             "prix": "Candidature sur <b>btpexpertise.fr/rejoignez-nous</b> · contact@btpexpertise.fr"},
        ],
    },
]
