# -*- coding: utf-8 -*-
"""Carrousels de novembre 2026 : 4 AMO, 4 Réseau, 1 Expertise (fuite encastrée).

Sources relues le 2026-10-08 : btpexpertise.fr/reglement/ (tarifs inchangés),
/amo/ (missions et projets accompagnés), /rejoignez-nous/ (profils, prérequis).
Les chargés d'affaires n'ont pas de carrousel : leur offre n'est pas encore
connue, on n'invente rien. R4 = thermicien en attendant.
"""

from carrousels import AMO, DESORDRES, PASTILLE_FIN, PRIX_AMO, PRIX_DESORDRES

CANDIDATURE = "Candidature sur <b>btpexpertise.fr/rejoignez-nous</b> · contact@btpexpertise.fr"


def principe():
    return {"type": "cartes", "gris": True, "surtitre": "Le principe", "titre": "Indépendant, pas isolé",
            "items": [("maison", "Votre structure", "Vous gardez votre statut et votre responsabilité professionnelle."),
                      ("reseau", "Des dossiers adaptés", "Le cabinet mobilise les compétences selon la spécificité de chaque dossier."),
                      ("doc", "Une méthode commune", "Constater, analyser, préconiser.")]}


def prerequis(experience):
    return {"type": "frise", "surtitre": "Les prérequis", "titre": "Ce que nous demandons",
            "items": [("Statut indépendant", "Installé à votre compte."),
                      ("Expérience terrain", experience),
                      ("RC professionnelle", "À jour."),
                      ("Secteur", "Alpes-Maritimes (06) et/ou Var (83).")]}


def fin_reseau(titre):
    return {"type": "contact", "pastille": "CANDIDATURE", "titre": titre, "taille": 72,
            "chapo": "Un premier échange téléphonique, sans engagement.",
            "boutons": ("Rejoignez-nous", "btpexpertise.fr"), "prix": CANDIDATURE}


NOVEMBRE = [
    # ------------------------------------------------------------------ AMO
    {
        "slug": "2026-11-amo-cadrage",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "plans-bureau.jpg", "cadrage": "center top", "pastille": AMO, "taille": 80,
             "titre": 'Le projet commence<br><span class="o">avant le premier devis.</span>',
             "chapo": "Sans cadrage, chaque entreprise chiffre un projet différent."},
            {"type": "cartes", "surtitre": "Sans cadrage", "titre": 'Trois entreprises, <span class="o">trois projets</span>',
             "items": [("x", "Des périmètres qui varient", "Chacun imagine ce que vous voulez."),
                       ("x", "Des choix laissés ouverts", "Matériaux et finitions au gré de l'entreprise."),
                       ("x", "Des devis incomparables", "On compare des projets, pas des prix.")]},
            {"type": "frise", "gris": True, "surtitre": "L'étude du projet", "titre": 'Poser les bonnes <span class="o">questions</span>',
             "items": [("Objectifs", "Ce que vous voulez obtenir, et pourquoi."),
                       ("Contraintes", "Bâti existant, copropriété, accès, délais."),
                       ("Priorités", "L'indispensable, le souhaitable, le reportable."),
                       ("Enveloppe", "Le budget que vous vous fixez.")]},
            {"type": "cartes", "couleur": "bleu", "surtitre": "La définition des travaux", "titre": 'Un même cahier pour <span class="o">tous</span>',
             "items": [("doc", "Prestations décrites", "Ce qui est attendu, poste par poste."),
                       ("barres", "Quantités", "Une base commune à toutes les entreprises."),
                       ("ok", "Consultation", "Chaque entreprise chiffre le même projet.")]},
            {"type": "duo", "gris": True, "surtitre": "Le résultat", "titre": 'Des devis enfin <span class="o">comparables</span>',
             "items": [("x", "Sans cadrage", "Trois devis, trois projets, aucun repère pour choisir."),
                       ("ok", "Avec cadrage", "Trois prix pour un même projet : la comparaison devient possible.")],
             "cle": "Vous restez décisionnaire : vous choisissez, et vous contractez directement avec l'entreprise."},
            {"type": "contact", "photo": "plans-bureau.jpg", "pastille": PASTILLE_FIN,
             "titre": 'Un projet de travaux ?<br><span class="o">Parlons-en.</span>',
             "chapo": "Un regard technique indépendant, dès la définition du besoin.", "prix": PRIX_AMO},
        ],
    },
    {
        "slug": "2026-11-amo-budget",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "budget-bureau.jpg", "cadrage": "center top", "pastille": AMO, "taille": 84,
             "titre": 'Votre budget va déraper.<br><span class="o">Voici pourquoi.</span>',
             "chapo": "Rarement à cause d'un seul poste. Souvent à cause de ce qui n'était pas écrit."},
            {"type": "cartes", "surtitre": "Les causes fréquentes", "titre": 'Là où l\'argent <span class="o">s\'échappe</span>',
             "items": [("alerte", "Les postes oubliés", "Dépose, évacuation, protections, raccords."),
                       ("alerte", "Les quantités floues", "Un « forfait » qui ne dit pas ce qu'il couvre."),
                       ("alerte", "Le bâti existant", "Ce qu'on découvre en ouvrant."),
                       ("alerte", "Les avenants", "Des modifications ajoutées en cours de route.")]},
            {"type": "frise", "gris": True, "surtitre": "Avant les travaux", "titre": 'Estimer pour <span class="o">décider</span>',
             "items": [("Estimer", "Un ordre de grandeur réaliste, poste par poste."),
                       ("Hiérarchiser", "L'indispensable, et ce qui peut attendre."),
                       ("Prévoir une marge", "Pour les aléas du bâti existant."),
                       ("Comparer les devis", "Sur un même périmètre.")]},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Pendant les travaux", "titre": 'Chaque avenant <span class="o">se discute</span>',
             "items": [("loupe", "Comprendre", "Pourquoi ce supplément, et était-il prévisible ?"),
                       ("doc", "Vérifier", "Le prix, au regard du devis initial."),
                       ("ok", "Décider", "En connaissance de cause, avant de signer.")]},
            {"type": "duo", "gris": True, "surtitre": "Le rôle de l'AMO", "titre": 'Éclairer, <span class="o">pas promettre</span>',
             "items": [("ok", "L'AMO fait", "Estimer, comparer, alerter, vous aider à décider."),
                       ("x", "L'AMO ne fait pas", "Garantir un budget ou un délai : la décision reste la vôtre.")]},
            {"type": "contact", "photo": "budget-bureau.jpg", "pastille": PASTILLE_FIN,
             "titre": 'Un budget travaux à cadrer ?<br><span class="o">Parlons-en.</span>', "taille": 74,
             "chapo": "Un regard technique indépendant avant de vous engager.", "prix": PRIX_AMO},
        ],
    },
    {
        "slug": "2026-11-amo-visite",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "visite-08.jpg", "pastille": AMO, "taille": 80,
             "titre": 'Ce qu\'une visite de chantier<br><span class="o">vérifie vraiment.</span>',
             "chapo": "Un regard technique sur place, aux moments qui comptent."},
            {"type": "frise", "surtitre": "Pendant la visite", "titre": 'Observer, <span class="o">pas diriger</span>',
             "items": [("Avancement", "Ce qui est fait, au regard du planning."),
                       ("Qualité apparente", "Finitions, alignements, défauts visibles."),
                       ("Points de vigilance", "Ce qui sera caché à l'étape suivante."),
                       ("Questions", "Celles à poser à l'entreprise.")]},
            {"type": "cartes", "gris": True, "surtitre": "Les bons moments", "titre": 'Avant que ce soit <span class="o">caché</span>',
             "items": [("cal", "Avant de fermer les cloisons", "Réseaux et supports encore visibles."),
                       ("cal", "Avant carrelage et étanchéité", "Supports, pentes, relevés."),
                       ("cal", "Avant la réception", "La liste des points à reprendre.")]},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Après la visite", "titre": 'Un compte rendu <span class="o">écrit</span>',
             "items": [("photo", "Photographies", "Datées et situées."),
                       ("doc", "Observations", "Ce qui va, ce qui pose question."),
                       ("alerte", "Recommandations", "Les points à faire reprendre, la suite à donner.")]},
            {"type": "duo", "gris": True, "surtitre": "Le cadre", "titre": 'Conseiller, <span class="o">pas commander</span>',
             "items": [("ok", "La visite AMO", "Observer, alerter, conseiller le maître d'ouvrage."),
                       ("x", "Ce qu'elle n'est pas", "Une direction de travaux : pas d'ordres aux entreprises.")],
             "cle": "Vous restez maître de votre projet : vous décidez, vous contractez directement avec les entreprises."},
            {"type": "contact", "photo": "visite-08.jpg", "pastille": PASTILLE_FIN,
             "titre": 'Des travaux en cours ?<br><span class="o">Parlons-en.</span>',
             "chapo": "Un regard technique de votre côté, pendant tout le chantier.", "prix": PRIX_AMO},
        ],
    },
    {
        "slug": "2026-11-amo-sinistre",
        "theme": "amo",
        "diapos": [
            {"type": "couverture", "photo": "visite-07.jpg", "pastille": AMO, "taille": 80,
             "titre": 'Après un sinistre,<br><span class="o">refaire… mais comment ?</span>',
             "chapo": "Entre assureur, experts et entreprises, le maître d'ouvrage est souvent seul."},
            {"type": "cartes", "surtitre": "La situation", "titre": 'Beaucoup d\'intervenants, <span class="o">peu de repères</span>',
             "items": [("alerte", "L'expert de l'assurance", "Il travaille pour son mandant."),
                       ("alerte", "Les entreprises", "Chacune propose sa solution, et son prix."),
                       ("alerte", "Vous", "Qui devez décider vite, sans tout maîtriser.")]},
            {"type": "frise", "gris": True, "surtitre": "Avant de reconstruire", "titre": 'Définir les <span class="o">travaux de reprise</span>',
             "items": [("Constater l'étendue", "Ce qui est touché, et ce qui ne l'est pas."),
                       ("Comprendre l'origine", "Pour ne pas reconstruire sur la même faiblesse."),
                       ("Décrire les reprises", "Poste par poste."),
                       ("Consulter", "Les entreprises, sur un même périmètre.")]},
            {"type": "cartes", "surtitre": "À éviter", "titre": 'Les pièges de <span class="o">l\'urgence</span>',
             "items": [("x", "Nettoyer avant de photographier", "Les preuves disparaissent."),
                       ("x", "Signer le premier devis", "Sans comparer ni vérifier le périmètre."),
                       ("x", "Refaire à l'identique", "Sans traiter la cause.")]},
            {"type": "cartes", "couleur": "bleu", "gris": True, "surtitre": "Pendant les reprises", "titre": 'Un regard technique <span class="o">à vos côtés</span>',
             "items": [("barres", "Analyse des devis", "Comparaison technique et financière."),
                       ("loupe", "Visites sur site", "Et comptes rendus."),
                       ("ok", "Assistance à réception", "Jusqu'à la formulation des réserves.")]},
            {"type": "contact", "photo": "visite-07.jpg", "pastille": PASTILLE_FIN,
             "titre": 'Un sinistre à remettre en état ?<br><span class="o">Parlons-en.</span>', "taille": 72,
             "chapo": "Un accompagnement technique face aux intervenants.", "prix": PRIX_AMO},
        ],
    },
    # --------------------------------------------------------------- Réseau
    {
        "slug": "2026-11-reseau-economiste",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Profil recherché", "titre": "Économiste de la construction",
             "items": ["Estimer des travaux, poste par poste", "Analyser et comparer des devis",
                       "Éclairer le choix des entreprises", "Alpes-Maritimes et Var"],
             "chapo": "Une compétence au cœur des missions d'assistance à maîtrise d'ouvrage."},
            {"type": "cartes", "surtitre": "Pourquoi ce profil", "titre": "Là où l'AMO a besoin de vous",
             "items": [("barres", "Estimation et budget", "Un ordre de grandeur réaliste avant de consulter."),
                       ("doc", "Analyse des devis", "Comparaison technique et financière des propositions."),
                       ("ok", "Aide au choix", "Une analyse des offres avant la décision du maître d'ouvrage.")]},
            principe(),
            prerequis("En économie de la construction."),
            fin_reseau('Les chiffres du bâtiment,<br><span class="b">c\'est votre métier ?</span>'),
        ],
    },
    {
        "slug": "2026-11-reseau-rapport",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Méthode", "titre": "Ce qui fait un rapport qui tient",
             "items": ["Des constats situés et photographiés", "Une cause rattachée aux règles de l'art",
                       "Des préconisations claires", "Les limites de la mission, écrites"],
             "chapo": "L'exigence que nous partageons avec les professionnels du réseau."},
            {"type": "frise", "surtitre": "Constater", "titre": "Décrire ce qui se voit",
             "items": [("Situer", "La pièce, l'élément, l'orientation."),
                       ("Mesurer", "Ouvertures, dimensions, relevés."),
                       ("Photographier", "Avec un repère d'échelle.")]},
            {"type": "frise", "gris": True, "surtitre": "Analyser", "titre": "Relier le désordre à une cause",
             "items": [("Hypothèses", "Les causes possibles, examinées une à une."),
                       ("Références", "DTU, règles de l'art, pièces du marché."),
                       ("Conclusion", "La cause probable, et son degré de certitude.")]},
            {"type": "cartes", "surtitre": "Préconiser", "titre": "Dire la suite, simplement",
             "items": [("alerte", "Priorités", "Ce qui est urgent, ce qui peut attendre."),
                       ("loupe", "Investigations", "Quand un sondage ou une étude s'imposent."),
                       ("doc", "Limites", "Ce que la mission n'a pas pu examiner.")]},
            fin_reseau('Vous partagez cette exigence ?<br><span class="b">Rejoignez le réseau.</span>'),
        ],
    },
    {
        "slug": "2026-11-reseau-couverture",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Profil recherché", "titre": "Spécialiste couverture et étanchéité",
             "items": ["Toitures-terrasses et relevés", "Couvertures en tuiles, zinguerie",
                       "Infiltrations : chercher l'origine", "Alpes-Maritimes et Var"],
             "chapo": "Avec les pluies d'automne, les dossiers d'infiltration se multiplient."},
            {"type": "cartes", "surtitre": "Les dossiers", "titre": "Là où votre regard compte",
             "items": [("loupe", "Relevés d'étanchéité", "Hauteur, fixation en tête, vieillissement."),
                       ("goutte", "Évacuations pluviales", "Sous-dimensionnées ou obstruées."),
                       ("maison", "Raccords", "Extensions, vérandas, souches de cheminée.")]},
            principe(),
            prerequis("En couverture et étanchéité."),
            fin_reseau('Les toitures,<br><span class="b">c\'est votre terrain ?</span>'),
        ],
    },
    {
        "slug": "2026-11-reseau-thermicien",
        "theme": "reseau",
        "diapos": [
            {"type": "titre", "label": "Profil recherché", "titre": "Thermicien du bâtiment",
             "items": ["Ponts thermiques et condensation", "Isolation et continuité",
                       "Ventilation et humidité", "Alpes-Maritimes et Var"],
             "chapo": "Moisissures, condensation, inconfort : des dossiers où la thermique fait la différence."},
            {"type": "cartes", "surtitre": "Les dossiers", "titre": "Là où votre regard compte",
             "items": [("goutte", "Condensation", "Trouver le point froid."),
                       ("maison", "Isolation", "Vérifier la continuité, pas seulement l'épaisseur."),
                       ("reseau", "Ventilation", "Un circuit complet, de l'entrée à l'extraction.")]},
            principe(),
            prerequis("En thermique du bâtiment."),
            fin_reseau('La thermique,<br><span class="b">c\'est votre spécialité ?</span>'),
        ],
    },
    # ------------------------------------------------------------ Expertise
    {
        "slug": "2026-11-fuite-encastree",
        "diapos": [
            {"type": "couverture", "photo": "visite-03.jpg", "pastille": DESORDRES, "taille": 80,
             "titre": 'Une facture d\'eau qui grimpe.<br><span class="o">Et rien ne coule.</span>',
             "chapo": "Une fuite encastrée se voit rarement. Elle se devine."},
            {"type": "cartes", "couleur": "bleu", "surtitre": "Les indices", "titre": 'Ce qui doit <span class="b">alerter</span>',
             "items": [("goutte", "Le compteur tourne", "Tous les robinets fermés."),
                       ("goutte", "Une tache qui s'étend", "Au sol, en pied de mur, au plafond du dessous."),
                       ("alerte", "Un carrelage qui sonne creux", "Ou des joints qui noircissent."),
                       ("alerte", "Une odeur d'humidité", "Persistante, sans cause visible.")]},
            {"type": "frise", "gris": True, "surtitre": "Le test simple", "titre": 'Vérifier au <span class="o">compteur</span>',
             "items": [("Fermer", "Tous les points d'eau de la maison."),
                       ("Relever", "L'index du compteur."),
                       ("Attendre", "Une à deux heures, sans tirer d'eau."),
                       ("Comparer", "Si l'index a bougé, l'eau part quelque part.")]},
            {"type": "cartes", "surtitre": "À éviter", "titre": 'Casser <span class="o">au hasard</span>',
             "items": [("x", "Ouvrir un mur à l'aveugle", "On multiplie les dégâts."),
                       ("x", "Repeindre la tache", "Elle revient, la fuite continue."),
                       ("x", "Attendre", "L'eau abîme les supports, et peut toucher le voisin.")]},
            {"type": "cartes", "couleur": "bleu", "gris": True, "etiquette": "J'AI UN PROBLÈME",
             "titre": 'Localiser avant de <span class="b">réparer</span>',
             "items": [("loupe", "Constater", "L'étendue des traces et des dégâts."),
                       ("barres", "Analyser", "L'origine probable : alimentation, évacuation, étanchéité."),
                       ("doc", "Préconiser", "Les investigations et les reprises adaptées.")]},
            {"type": "contact", "photo": "visite-03.jpg", "pastille": PASTILLE_FIN,
             "titre": 'Une fuite introuvable ?<br><span class="o">Parlons-en.</span>',
             "chapo": "Comprendre d'où vient l'eau avant d'ouvrir les murs.", "prix": PRIX_DESORDRES},
        ],
    },
]
